export  const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  REMOVE_PRODUCT:"REMOVE_PRODUCT",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  ADD_TO_CART:"ADD_TO_CART",
  REMOVE_TO_CART:"REMOVE_TO_CART",
  SUB_TO_CART:"SUB_TO_CART",
  SET_SEARCH:"SET_SEARCH",
  ADD_PRODUCT_CATAGORY:"ADD_PRODUCT_CATAGORY",
  ADD_ALL_CATAGORY_PRODUCT:"ADD_ALL_CATAGORY_PRODUCT",
  REMOVE_ALL_CATAGORY_PRODUCT:"REMOVE_ALL_CATAGORY_PRODUCT"
};
